import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: '{{APP_NAME}}',
  description: 'Generated by the Avani Calibration Engine',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>{{APP_NAME}}</h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
