import type { CalibratedConfig } from '../schema/calibrated-config.js';
import { PROVISION_BY_ID } from '../selection/catalog.js';
import type { Selection } from '../selection/select.js';
import { byKind } from './helpers.js';

/**
 * Build the project CLAUDE.md — the thin, project-specific advisory layer.
 * Deep knowledge lives in the enabled plugins; this file only carries what is
 * specific to *this* project. Kept short by design.
 */
export function buildClaudeMd(config: CalibratedConfig, selection: Selection): string {
  const plugins = byKind(selection, 'plugin');
  const invariants = config.invariants;
  const isNext = config.dials.runtime === 'ts-nextjs';

  const lines: string[] = [];
  lines.push(`# ${config.profile}`, '');
  lines.push('> Generated by the Avani Calibration Engine. Deep conventions live in the enabled plugins; this file is the project-specific layer.', '');

  lines.push('## Architecture', '');
  lines.push(`- **Runtime:** ${config.dials.runtime}`);
  lines.push(`- **Infra:** ${config.dials.infra}`);
  lines.push(`- **Topology:** ${config.dials.topology}`);
  lines.push(`- **Correctness bar:** ${config.dials.correctness_bar}`);
  lines.push(`- **Sensitivity:** ${config.dials.sensitivity}`, '');

  lines.push('## Stage', '');
  lines.push('Enforcement escalates with the project stage. Resolve it from `AVANI_STAGE` (`dev` | `staging` | `production`), falling back to the branch (`feature/*` → dev, `main` → staging, release → production). Check it before prod-affecting actions.', '');

  if (isNext) {
    lines.push('## Commands', '');
    lines.push('```bash');
    lines.push('npm run db:migrate:dev      # create + apply a migration in dev');
    lines.push('npm run db:migrate:deploy   # apply pending migrations (prod/deploy)');
    lines.push('npm run db:reset            # reset the dev database (DEV ONLY)');
    lines.push('npm run db:seed             # seed local data');
    lines.push('```', '');
  }

  lines.push('## Deploy', '');
  const d = config.decisions?.infra;
  const provenance = d
    ? d.status === 'decided'
      ? `proposed by the engine (§4.1 rule ${d.rule}), decided by the owner${d.note ? ` — ${d.note}` : ''}`
      : `PROPOSED by the engine (§4.1 rule ${d.rule}) and not yet decided — the owner accepts or overrides it (\`calibrate --infra <target>\`) before anything deploys`
    : 'set at calibration';
  lines.push(`- **Target:** \`${config.dials.infra}\` — ${provenance}. A human decision recorded in \`.avani/manifest.json\` and the roadmap decision log, never a per-session choice. It selects the deploy profile that fixes where migrations run, how secrets reach the platform, what is backed up, and the production gate.`);
  lines.push('- Production is deployed only by CI under the production gate. Sessions and subagents prepare changes (workflow, config, infrastructure code with its plan or diff) and never deploy, apply, or touch a live environment themselves.');
  lines.push('- Procedure: the `avani-core` `deployment` skill — three environments, migrate before deploy, forward-only releases, backup before data-shape changes. Role bounds: `.claude/agents/`.', '');

  lines.push('## Invariants (enforced)', '');
  for (const inv of invariants) {
    const desc = PROVISION_BY_ID.get(`invariant:${inv}`)?.description ?? '';
    lines.push(`- \`${inv}\` — ${desc}`);
  }
  lines.push('', 'Tests live in `tests/invariants/`. Do not weaken them to make a change pass; if an invariant is wrong, change it deliberately.', '');

  lines.push('## Enabled plugins', '');
  lines.push(plugins.map((p) => `\`${p}\``).join(', '), '');

  lines.push('## Gotchas', '');
  if (config.dials.correctness_bar === 'append-only') {
    lines.push('- Data is **append-only**: never delete or hard-update records; supersede with a correction.');
  }
  if (config.dials.sensitivity === 'protected') {
    lines.push('- Location data is **protected**: public views must fuzz coordinates; exact coords are admin-only.');
  }
  if (isNext) {
    lines.push('- Never `prisma db push` against a non-dev database; migrations only, applied on deploy.');
  }
  lines.push('');

  return lines.join('\n');
}
